#!/usr/bin/env python3

import os, sys, json
from flask import Flask
from flask import request
from flask_cors import CORS
import subprocess

dir = os.path.dirname(os.path.realpath(__file__))

string = 'some data'

app = Flask(__name__)
app.debug = True
CORS(app)

def log(*msg):
  print(*msg, file=sys.stderr)

@app.route('/', methods=['GET'])
def hello():
  return 'YAML'

@app.route('/', methods=['POST'])
def processYaml():
  cmd = request.args.get('cmd')
  yaml = request.form.get('text')

  command = ['timeout', '1', '/usr/local/bin/' + cmd]

  result = subprocess.run(
    command,
    input=yaml.encode(),
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
  )

  status = result.returncode
  output = result.stdout.decode()

  resp = {
    'status': status,
    'output': output,
  }

  return json.dumps(resp)

if __name__ == "__main__":
  host = '0.0.0.0'

  if sys.argv[1] == 'https':
    port = '31337'
    ssl_context = 'adhoc'
  elif sys.argv[1] == 'http':
    port = '1337'
    ssl_context = None
  else:
    raise ValueError("Invalid argument '%s'" % sys.argv[1])

  app.run(
    ssl_context=ssl_context,
    host=host,
    port=port,
  )
