#!/usr/bin/env python3

import os, sys, json
from flask import Flask
from flask import request
from flask_cors import CORS
import subprocess

dir = os.path.dirname(os.path.realpath(__file__))

required_version = open('/sandbox_version').read().rstrip()

app = Flask(__name__)
app.debug = True
CORS(app)

def log(*msg):
  app.logger.info(str(msg))

@app.route('/', methods=['GET'])
def hello():
  return '''
<h2>Success!</h2>
<script>
setTimeout(function() {
  alert("HTTPS Enabled!\\n\\nClick OK to close, then reload the Playground.");
  window.close();
},1000);
</script>
'''

@app.route('/', methods=['POST'])
def processYaml():
  version = request.args.get('version')
  if version != required_version:
    raise(Exception("Requires sandbox version %s" % required_version))

  bin = request.args.get('parser')
  yaml = request.form.get('text')

  command = ['timeout', '1', '/usr/local/bin/' + bin]

  result = subprocess.run(
    command,
    input=yaml.encode(),
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
  )

  status = result.returncode
  output = result.stdout.decode()

  if status == 124 or status == 143:
    output = "TIMEOUT - PROCESS TERMINATED\n\n" + output

  data = {
    'status': status,
    'output': output,
  }

  # return json.dumps(data)

  response = app.response_class(
    response=json.dumps(data),
    status=200,
    mimetype='application/json'
  )

  origin = request.headers.get('Origin', '')
  if origin.endswith('play.yaml.io'):
    response.headers['Access-Control-Allow-Origin'] = origin

  return response

if __name__ == "__main__":
  host = '0.0.0.0'

  port = sys.argv[1]
  if sys.argv[1] == '1337':
    ssl_context = None
  else:
    ssl_context = 'adhoc'

  app.run(
    ssl_context=ssl_context,
    host=host,
    port=port,
  )
